export const Quizdata=[
    {
        question:["地震が起きました。","まず起こす行動は？",],
        answerA:"だんごむしの姿勢をとる",
        answerB:"さけぶ",
        answerC:"とりあえずトイレへ行く",
        answerD:"ゲームをする",
        true_answer:"だんごむしの姿勢をとる"
    },
    {
        question:["海に近い所で地震が起きました。",
        "どのような行動をしますか？"],
        answerA:"誰かに連絡する",
        answerB:"高い所へ避難する",
        answerC:"あきらめる",
        answerD:"その場で動かない",
        true_answer:"高い所へ避難する"
    },
    {
        question:["火を使っているときに地震が起きました。",
        "どうしますか？"],
        answerA:"ゆれが治まってから火を消す",
        answerB:"火は消さなくてよい",
        answerC:"すぐに火を消す",
        answerD:"そのまま調理を続ける",
        true_answer:"ゆれが治まってから火を消す"
    },
    {
        question:["災害時、水や食料は最低何日分用意しますか？"],
        answerA:"1日",
        answerB:"3日",
        answerC:"7日",
        answerD:"14日",
        true_answer:"7日"
    },
    {
        question:["机に隠れる事が、難しいほどの大地震が起きました。",
        "どうしますか？"],
        answerA:"しょうがないので急いで外に避難する",
        answerB:"落下物がない所へ行く",
        answerC:"維持でも隠れる",
        answerD:"運頼みでうつ伏せになる",
        true_answer:"落下物がない所へ行く"
    },
    {
        question:["家族と離れた所で地震が起きました。",
        "合流するにはどのようなことをしたらいいでしょう？"],
        answerA:"例え危険でも家に戻る",
        answerB:"電話をかける",
        answerC:"大声で呼ぶ",
        answerD:"家族であらかじめ集合場所に行く",
        true_answer:"家族であらかじめ集合場所に行く"
    },
    {
        question:["地震が起こった後は火災が起こるかもしれません。",
        "火災予防として何をすべきでしょう？"],
        answerA:"何もしなくてもよい",
        answerB:"ブレーカーを落とす",
        answerC:"コンセントをすべて抜いておく",
        answerD:"すぐに消火できるように消火栓を買っておく",
        true_answer:"ブレーカーを落とす"
    },
    {
        question:["トイレにいるときに地震が起こったらどうしますか？"],
        answerA:"ドアを開ける",
        answerB:"とりあえず出しきる",
        answerC:"すぐに外に出る",
        answerD:"ドアを開けずに身を守る",
        true_answer:"ドアを開ける"
    },
    {
        question:["地震が起きたときまず何をするべき？"],
        answerA:"スマホで情報収集",
        answerB:"友達と会話",
        answerC:"自分の身を守る",
        answerD:"家族の安否確認",
        true_answer:"自分の身を守る"
    },
    {
        question:["避難中に寒くなりました。","上着代わりになるものとは何？"],
        answerA:"ビニール袋",
        answerB:"傘",
        answerC:"草",
        answerD:"新聞紙",
        true_answer:"新聞紙"
    },
    {
        question:["エレベーターの中で地震が起きました。",
        "どのような行動をしますか？"],
        answerA:"行きたい階へ移動する",
        answerB:"すべての階のボタンをおして、止まった階で降りる",
        answerC:"その場で動かない",
        answerD:"エレベーターの中であばれまわる",
        true_answer:"すべての階のボタンをおして、止まった階で降りる"
    },
    {
        question:["大人1人に必要な飲料水は何リットルでしょうか？"],
        answerA:"1リットル",
        answerB:"2リットル",
        answerC:"3リットル",
        answerD:"4リットル",
        true_answer:"3リットル"
    },
    {
        question:["近くに歩くことができない怪我人がいます。",
        "担架の代わりになるものはなんでしょう？"],
        answerA:"毛布",
        answerB:"段ボール",
        answerC:"枝",
        answerD:"新聞紙",
        true_answer:"毛布"
    },
    {
        question:["屋外で雷が鳴り始めました。",
        "どこにいたら一番安全でしょう？"],
        answerA:"木の下",
        answerB:"車の中",
        answerC:"できるだけ広い場所",
        answerD:"鉄塔の近く",
        true_answer:"車の中"
    },
    {
        question:["災害に関する情報は何で確認するといいでしょうか？"],
        answerA:"テレビ",
        answerB:"ユーチューブ",
        answerC:"自分で聞きに行く",
        answerD:"ラジオ",
        true_answer:"ラジオ"
    },
    {
        question:["人は一定の高さを超えた津波が起こった場合ほぼ助からないと言われています。",
        "その高さとは何cmでしょう？"],
        answerA:"30cm",
        answerB:"50cm",
        answerC:"70cm",
        answerD:"100cm",
        true_answer:"100cm"
    },
    {
        question:["火災が発生したとき役立つものとはなんでしょう？"],
        answerA:"スマホ",
        answerB:"ビニール袋",
        answerC:"ペットボトル",
        answerD:"マスク",
        true_answer:"ビニール袋"
    },
    {
        question:["海岸付近での津波の伝わる速さどれくらいでしょう？"],
        answerA:"時速10km",
        answerB:"時速20km",
        answerC:"時速30km",
        answerD:"時速40km",
        true_answer:"時速40km"
    },
    {
        question:["歩道橋にいるときに地震が起きました。",
        "どのような行動をとりますか？"],
        answerA:"急いで歩道橋をおりる",
        answerB:"手すりなどにつかまって揺れが止まるのを待つ",
        answerC:"ゆっくり歩道橋をおりる",
        answerD:"うつ伏せになる",
        true_answer:"手すりなどにつかまって揺れが止まるのを待つ"
    },
    {
        question:["阪神淡路大震災の後2ヶ月間で起こった余震は何回起こったでしょう？"],
        answerA:"100回",
        answerB:"500回",
        answerC:"1000回",
        answerD:"1700回",
        true_answer:"1700回"
    }
]